### ISSUE TITLE
Connect_Disconnect_Mars inconsistent

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-ipfs-engine#55]
```
Failed   Connect_Disconnect_Mars
Error Message:
 Test method Ipfs.Engine.SwarmApiTest.Connect_Disconnect_Mars threw exception:
System.Exception: Cannot dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ. ---> System.OperationCanceledException: The operation was canceled.
Stack Trace:
    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at PeerTalk.TaskHelper.<WhenAnyResult>d__0`1.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\TaskWhenAnyResult.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PeerTalk.Swarm.<Dial>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 497
--- End of inner exception stack trace ---
    at PeerTalk.Swarm.<Dial>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 503
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PeerTalk.Swarm.<ConnectAsync>d__44.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PeerTalk.Swarm.<ConnectAsync>d__43.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 364
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ipfs.Engine.CoreApi.SwarmApi.<ConnectAsync>d__5.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\src\CoreApi\SwarmApi.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ipfs.Engine.SwarmApiTest.<Connect_Disconnect_Mars>d__3.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\test\CoreApi\SwarmApiTest.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Ipfs.Engine.SwarmApiTest.<Connect_Disconnect_Mars>d__3.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\test\CoreApi\SwarmApiTest.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```
```
Standard Output Messages:
 17:12:12.138 [DEBUG] Ipfs.Engine.IpfsEngine - starting Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ
 17:12:12.138 [DEBUG] PeerTalk.Swarm - Starting
 17:12:12.138 [DEBUG] Ipfs.Engine.IpfsEngine - waiting for services to start
 17:12:12.138 [DEBUG] PeerTalk.Discovery.Bootstrap - Starting
 17:12:12.138 [DEBUG] Ipfs.Engine.BlockExchange.Bitswap - Starting
 17:12:12.138 [DEBUG] PeerTalk.Routing.Dht1 - Starting
 17:12:12.138 [DEBUG] PeerTalk.Swarm - new peer QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
 17:12:12.144 [DEBUG] PeerTalk.Swarm - new peer QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
 17:12:12.145 [DEBUG] PeerTalk.Swarm - new peer QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
 17:12:12.145 [DEBUG] PeerTalk.Swarm - new peer QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
 17:12:12.149 [DEBUG] PeerTalk.Swarm - new peer QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
 17:12:12.193 [DEBUG] PeerTalk.Protocols.Multistream1 - switching to /ipfs/id/1.0.0
 17:12:12.193 [DEBUG] PeerTalk.Protocols.Identify1 - Sending identity to /ip4/213.127.4.117/tcp/8115/ipfs/QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v
 17:12:12.195 [DEBUG] PeerTalk.Protocols.Identify1 - Peer id 'QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v' of /ip4/213.127.4.117/tcp/8115/ipfs/QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v
 17:12:12.245 [DEBUG] PeerTalk.Protocols.Identify1 - Get remote identity
 17:12:12.251 [DEBUG] Ipfs.Engine.IpfsEngine - all service started
 17:12:12.251 [DEBUG] PeerTalk.Transports.Tcp - listening on /ip4/0.0.0.0/tcp/64301
 17:12:12.372 [WARN]  PeerTalk.Multiplex.Muxer - Reset of unknown stream #1002
 17:12:12.453 [DEBUG] PeerTalk.Protocols.Identify1 - Get remote identity
 17:12:12.538 [DEBUG] Makaretu.Dns.MulticastService - Found nic 'Npcap Loopback Adapter'.
 17:12:12.538 [DEBUG] Makaretu.Dns.MulticastService - Found nic 'Wi-Fi'.
 17:12:12.691 [DEBUG] PeerTalk.Discovery.Mdns - Advertising ciqousjmcy4po464jhlhltuf7uzsivcg2qenzw5ax3wu5os5yoe5cbi._p2p._udp.local
 17:12:12.692 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _p2p._udp.local PTR
 17:12:12.692 [DEBUG] PeerTalk.Discovery.Mdns - Advertising Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ.ipfs.local
 17:12:12.695 [DEBUG] PeerTalk.Discovery.Mdns - Advertising Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ._ipfs-discovery._udp.local
 17:12:12.696 [DEBUG] Ipfs.Engine.IpfsEngine - started
 17:12:12.697 [DEBUG] Makaretu.Dns.ServiceDiscovery - sent answer _p2p._udp.local IN PTR ciqousjmcy4po464jhlhltuf7uzsivcg2qenzw5ax3wu5os5yoe5cbi._p2p._udp.local
 17:12:12.697 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for ipfs.local PTR
 17:12:12.697 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for ipfs.local PTR
 17:12:12.699 [DEBUG] Makaretu.Dns.ServiceDiscovery - sent answer ipfs.local IN PTR Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ.ipfs.local
 17:12:12.699 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for ipfs.local PTR
 17:12:12.700 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _ipfs-discovery._udp.local PTR
 17:12:12.700 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _ipfs-discovery._udp.local PTR
 17:12:12.700 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _ipfs-discovery._udp.local PTR
 17:12:12.702 [DEBUG] Makaretu.Dns.ServiceDiscovery - sent answer _ipfs-discovery._udp.local IN PTR Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ._ipfs-discovery._udp.local
 17:12:12.705 [DEBUG] PeerTalk.Protocols.Identify1 - Peer id 'QmPwPMqySHKS9h8mrbMZz5SMvdzQmy4ZHMFyiiGsznBQie' of /ip4/219.235.12.149/tcp/4001/ipfs/QmPwPMqySHKS9h8mrbMZz5SMvdzQmy4ZHMFyiiGsznBQie
 17:12:13.014 [DEBUG] PeerTalk.SecureCommunication.Secio1 - Secure session established
 17:12:13.201 [WARN]  PeerTalk.Multiplex.Muxer - Reset of unknown stream #1002
 17:12:13.812 [WARN]  PeerTalk.Multiplex.Muxer - Reset of unknown stream #1002
 17:12:13.876 [DEBUG] PeerTalk.Protocols.Identify1 - Peer id 'QmRFS7Kfo6Hn16faNFt8RgEqE2khrSBH6WdhZvzLWTWiYv' of /ip6/2a03:b0c0:1:e0::13a:2001/tcp/4001/ipfs/QmRFS7Kfo6Hn16faNFt8RgEqE2khrSBH6WdhZvzLWTWiYv
 17:12:13.943 [WARN]  PeerTalk.Multiplex.Muxer - Reset of unknown stream #1002
 17:12:14.216 [DEBUG] Ipfs.Engine.BlockExchange.Bitswap - QmYk9yh9CUdZgFCprWbMoEibetq8eUWNLyZCFZxmAyLnmF refused /ipfs/bitswap/1.0.0
 =======================================================(inner most exception)===
  (1) System.OperationCanceledException
 ================================================================================
 Method        :  ThrowOperationCanceledException
 Type          :  System.Threading.CancellationToken
 Assembly      :  mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
 Assembly Path :  C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
 Source        :  mscorlib
 Thread        :  7 ''
 Helplink      :

 Message:
 "The operation was canceled."

 Properties:
   OperationCanceledException.CancellationToken = "System.Threading.CancellationToken"

 Stack Trace:
    at System.Threading.CancellationToken.ThrowOperationCanceledException()
    at PeerTalk.TaskHelper.<WhenAnyResult>d__0`1.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\TaskWhenAnyResult.cs:line 0
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at PeerTalk.Swarm.<Dial>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 497
 ================================================================================
 ================================================================================
  (2) System.Exception
 ================================================================================
 Method        :  MoveNext
 Type          :  PeerTalk.Swarm+<Dial>d__46
 Assembly      :  PeerTalk, Version=0.42.0.0, Culture=neutral, PublicKeyToken=null
 Assembly Path :  C:\Users\Owner\Documents\GitHub\net-ipfs-engine\test\bin\Release\net461\PeerTalk.dll
 Source        :  PeerTalk
 Thread        :  7 ''
 Helplink      :

 Message:
 "Cannot dial QmYk9yh9CUdZgFCprWbMoEibetq8eUWNLyZCFZxmAyLnmF."

 Stack Trace:
    at PeerTalk.Swarm.<Dial>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 503
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at PeerTalk.Swarm.<ConnectAsync>d__44.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 394
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at PeerTalk.Swarm.<DialAsync>d__45.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 430
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Ipfs.Engine.BlockExchange.Bitswap.<SendWantListAsync>d__24.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\src\BlockExchange\Bitswap.cs:line 276
 ================================================================================

 17:12:14.218 [WARN]  Ipfs.Engine.BlockExchange.Bitswap - QmYk9yh9CUdZgFCprWbMoEibetq8eUWNLyZCFZxmAyLnmF does not support any bitswap protocol
 17:12:14.229 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/207.246.91.167/tcp/46877/ipfs/QmSaGHyrf7Fi7Z7pHW2Pv3MLmRD2ujYzAcbYGG9hHduKwH
 17:12:14.229 [DEBUG] Ipfs.Engine.BlockExchange.Bitswap - QmSaGHyrf7Fi7Z7pHW2Pv3MLmRD2ujYzAcbYGG9hHduKwH refused /ipfs/bitswap/1.1.0
 =======================================================(inner most exception)===
  (1) System.Exception
 ================================================================================
 Method        :  MoveNext
 Type          :  PeerTalk.PeerConnection+<EstablishProtocolAsync>d__48
 Assembly      :  PeerTalk, Version=0.42.0.0, Culture=neutral, PublicKeyToken=null
 Assembly Path :  C:\Users\Owner\Documents\GitHub\net-ipfs-engine\test\bin\Release\net461\PeerTalk.dll
 Source        :  PeerTalk
 Thread        :  7 ''
 Helplink      :

 Message:
 "QmSaGHyrf7Fi7Z7pHW2Pv3MLmRD2ujYzAcbYGG9hHduKwH does not support protocol '/mplex/'."

 Stack Trace:
    at PeerTalk.PeerConnection.<EstablishProtocolAsync>d__48.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\PeerConnection.cs:line 244
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at PeerTalk.PeerConnection.<InitiateAsync>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\PeerConnection.cs:line 192
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at PeerTalk.Swarm.<Dial>d__46.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 527
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at PeerTalk.Swarm.<ConnectAsync>d__44.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 394
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at PeerTalk.Swarm.<DialAsync>d__45.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\PeerTalk\src\Swarm.cs:line 430
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Ipfs.Engine.BlockExchange.Bitswap.<SendWantListAsync>d__24.MoveNext() in C:\Users\Owner\Documents\GitHub\net-ipfs-engine\src\BlockExchange\Bitswap.cs:line 276
 ================================================================================

 17:12:14.270 [DEBUG] PeerTalk.SecureCommunication.Secio1 - Secure session established
 17:12:14.317 [DEBUG] PeerTalk.Routing.DistributedQuery - Q1.1.32 ask QmcV2z24BFPWnPUi7rgDyHrE8C183UNF1huFmZCETyRUbp
 17:12:14.331 [DEBUG] PeerTalk.Protocols.Identify1 - Peer id 'QmbbdJrNE2NcbyCkgw1cvFAYtH3vEiRWuCAaT2J49jouoL' of /ip4/134.175.173.176/tcp/4001/ipfs/QmbbdJrNE2NcbyCkgw1cvFAYtH3vEiRWuCAaT2J49jouoL
 17:12:14.498 [DEBUG] PeerTalk.SecureCommunication.Secio1 - Secure session established
 17:12:14.803 [WARN]  PeerTalk.Routing.DistributedQuery - Q20.1.1 ask failed 'Cannot dial QmSuSs6m2ZL6kR4cL7MYrZS2S7WuCEcXf4H3bZnJPodVPX.'
 17:12:14.804 [DEBUG] PeerTalk.Routing.DistributedQuery - Q20.1.2 ask QmNjm16wkUUsUoRmr3b8QoQAPZYBwfBHcygkjGbSauTSWu
 17:12:15.057 [DEBUG] PeerTalk.Routing.DistributedQuery - Q1.3.27 ask QmXLe5krX55mk9pj26wbSvXoNuCUqeGUeCC4agi5tSiv2M
 17:12:15.185 [DEBUG] PeerTalk.Protocols.Identify1 - Get remote identity
 17:12:15.327 [WARN]  PeerTalk.Multiplex.Muxer - Reset of unknown stream #1002
 17:12:15.495 [DEBUG] PeerTalk.SecureCommunication.Secio1 - Secure session established
 17:12:15.718 [DEBUG] PeerTalk.Protocols.Identify1 - Get remote identity
 17:12:15.731 [DEBUG] Ipfs.Engine.IpfsEngine - stopping
 17:12:15.731 [DEBUG] PeerTalk.Swarm - Stoping Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ
 17:12:15.731 [DEBUG] PeerTalk.Transports.Tcp - Got cancel on /ip4/0.0.0.0/tcp/64301
 17:12:15.731 [DEBUG] PeerTalk.Routing.Dht1 - Stopping
 17:12:15.731 [DEBUG] Ipfs.Engine.BlockExchange.Bitswap - Stopping
 17:12:15.731 [DEBUG] PeerTalk.Discovery.Bootstrap - Stopping
 17:12:15.732 [DEBUG] PeerTalk.Transports.Tcp - stop listening on /ip4/0.0.0.0/tcp/64301
 17:12:15.767 [DEBUG] PeerTalk.SecureCommunication.Secio1 - Secure session established
 17:12:15.822 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/172.65.0.13/tcp/4001/ipfs/QmNjm16wkUUsUoRmr3b8QoQAPZYBwfBHcygkjGbSauTSWu
 17:12:15.823 [WARN]  PeerTalk.Routing.DistributedQuery - Q20.1.2 ask failed 'QmNjm16wkUUsUoRmr3b8QoQAPZYBwfBHcygkjGbSauTSWu does not support protocol '/mplex/'.'
 17:12:15.826 [DEBUG] PeerTalk.Routing.DistributedQuery - Q20.1.3 ask QmSnGKkxy1LdTsFoeKvCNtEUD5d178Rk3xmufE3DHvcMsa
 17:12:15.839 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/219.235.12.149/tcp/4001/ipfs/QmPwPMqySHKS9h8mrbMZz5SMvdzQmy4ZHMFyiiGsznBQie
 17:12:15.840 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/147.135.130.181/tcp/4001/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic
 17:12:15.841 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/47.52.241.73/tcp/4001/ipfs/QmS4j8mqBctksR1hMkrdsvQEK3de4xmY51hfwo3Afwb6X8
 17:12:15.842 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip6/2a03:b0c0:1:e0::13a:2001/tcp/4001/ipfs/QmRFS7Kfo6Hn16faNFt8RgEqE2khrSBH6WdhZvzLWTWiYv
 17:12:15.843 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/180.97.68.9/tcp/4001/ipfs/QmdMoFr2CYiPQfjYeCSYupzmnnjpv2kPcAMbZ6zYfNbDnj
 17:12:15.843 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/134.175.173.176/tcp/4001/ipfs/QmbbdJrNE2NcbyCkgw1cvFAYtH3vEiRWuCAaT2J49jouoL
 17:12:15.844 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/134.175.173.176/tcp/4001/ipfs/QmbbdJrNE2NcbyCkgw1cvFAYtH3vEiRWuCAaT2J49jouoL
 17:12:15.844 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/213.127.4.117/tcp/8115/ipfs/QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v
 17:12:15.845 [DEBUG] PeerTalk.PeerConnection - Closing connection to /ip4/188.165.149.230/tcp/4001/ipfs/QmT67kjZEsvRupUmScrEnh53rnwCd8LCGM6pxTmyjFQD3d
 17:12:15.845 [DEBUG] PeerTalk.Swarm - Stoped Qme7CpnWmMWyakLJXZaLhVHpbX12FodX1vrnYGaQ41pndJ
 17:12:15.947 [DEBUG] Ipfs.Engine.IpfsEngine - stopped
```

**Comment by richardschneider** [comment]
How can `Multistream1` receive something before the engine is started?

```
 17:12:12.193 [DEBUG] PeerTalk.Protocols.Multistream1 - switching to /ipfs/id/1.0.0
 17:12:12.193 [DEBUG] PeerTalk.Protocols.Identify1 - Sending identity to /ip4/213.127.4.117/tcp/8115/ipfs/QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v
 17:12:12.195 [DEBUG] PeerTalk.Protocols.Identify1 - Peer id 'QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v' of /ip4/213.127.4.117/tcp/8115/ipfs/QmbUu4p2oFbpQ9MV66K5f7rSKazajc5aasmBKy24TMyP7v
 17:12:12.245 [DEBUG] PeerTalk.Protocols.Identify1 - Get remote identity
 17:12:12.251 [DEBUG] Ipfs.Engine.IpfsEngine - all service started
```
