### ISSUE TITLE
Randomly Failing Tests

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-ipfs-engine#74]
`DhtApiTest.FindProvider` and `SwarmApiTest.Connect_Disconnect_Mars` are sometimes failing; see https://ci.appveyor.com/project/richardschneider/net-ipfs-engine/builds/23525880

For now, these tests will be ignored.

**Comment by richardschneider** [comment]
`FileSystemApiTest.ReadTextFromNetwork` is sometimes failing.

**Comment by richardschneider** [comment]
```
Failed   AddFile_WithProgress
Error Message:
 Assert.AreEqual failed. Expected:<11>. Actual:<9>. 
Stack Trace:
   at Ipfs.Engine.FileSystemApiTest.<AddFile_WithProgress>d__21.MoveNext() in C:\projects\net-ipfs-engine\test\CoreApi\FileSystemApiTest.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
Standard Output Messages:
 20:56:49.992 [DEBUG] Ipfs.Engine.CoreApi.BlockApi - Block 'base58btc cidv0 dag-pb sha2-256 QmevnC4UDUWzJYAQtUSQw4ekUdqDqwcKothjcobE7byeb6' already present
 20:56:49.992 [DEBUG] Ipfs.Engine.CoreApi.BlockApi - Block 'base58btc cidv0 dag-pb sha2-256 QmTdBogNFkzUTSnEBQkWzJfQoiWbckLrTFVDHFRKFf6dcN' already present
 20:56:49.992 [DEBUG] Ipfs.Engine.CoreApi.BlockApi - Block 'base58btc cidv0 dag-pb sha2-256 QmPdmF1n4di6UwsLgW96qtTXUsPkCLN4LycjEUdH9977d6' already present
 20:56:49.993 [DEBUG] Ipfs.Engine.CoreApi.BlockApi - Block 'base58btc cidv0 dag-pb sha2-256 QmXh5UucsqF8XXM8UYQK9fHXsthSEfi78kewr8ttpPaLRE' already present
 20:56:49.993 [DEBUG] Ipfs.Engine.CoreApi.BlockApi - Block 'base58btc cidv0 dag-pb sha2-256 QmVVZXWrYzATQdsKWM4knbuH5dgHFmrRqW3nJfDgdWrBjn' already present
```

**Comment by richardschneider** [comment]
`Mars_Info` test is randomly failing to find peer.
